---
- name: Rewrite nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Make sure SSL dirs exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/pki/nginx/private
    - /etc/pki/nginx

- name: Copy site SSL cert
  copy:
    src: site_ssl.cert
    dest: /etc/pki/nginx/server.crt
  notify: Restart nginx

- name: Copy site SSL key
  copy:
    src: site_ssl.key
    dest: /etc/pki/nginx/private/server.key
  notify: Restart nginx
